#!/usr/bin/env python3

import in_place
import sys
from pathlib import Path

# textfile = input("Enter the name of the text file that needs to be changed: ")
# find_text = input("Enter text or string that needs to be changed: ")
# replace_text = input("Enter text that will be replacing the original text: ")

def str_replace(argv):
    """
    This python script takes filename as an input along with text that needs to be replaced and the text that it will be replaced with. 

    Usage:
    > str_replace_in_file <file_name> <input_text> <replace_text>
    """
    textfile = Path(sys.argv[1])
    find_text = sys.argv[2]
    replace_text = sys.argv[3]
    # print(sys.argv)

    with in_place.InPlace(textfile) as file:
        for line in file:
            line = line.replace(find_text, replace_text)
            file.write(line)


if __name__ == "__main__":
    str_replace(sys.argv[1:])
